### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by wothke** [gzaffin/eupmini#1]
The links to [http://mdxoarchive.webcrow.jp](http://mdxoarchive.webcrow.jp/EUP/FCEUP.part01.rar) (etc) no longer seem to work. Are there other sources where .eup files can be found?

**Comment by gzaffin** [comment]
I searched here and there and I could not find these files anywhere. So I created a shared folder on onedrive.
I updated Readme.md accordingly.
Please let me know if read permission on these files works for You.

**Comment by wothke** [comment]
thanks! I could download the files just fine..

btw.. do you have any background information regarding the origin of respective EUP songs? The title of the "TOWNS EUP 2015" suggests that these songs might have been created somewhat recently. is there some kind of "scene" that still creates new songs?
Do you know what the "FC6" (etc) folder names refer to? I noticed that the wineup.exe player that I tried for testing comes with "alb" (album?) files that use simular names (fc06.alb, etc) - though there seem to be many files in those "alb" lists that do not seem to be part of the FCEUP archives,,

**Comment by wothke** [comment]
ps: I just translated the "readme" in one of the songs and it mentions "Free Collection 3, 4, 5" so I guess that might be what the "FC" stands for.. I wonder if those other FCs might still be around somewhere..

**Comment by gzaffin** [comment]
If You have a bit of time You can go to [archive.org FM Towns free software collection list](https://archive.org/details/@shivashaw?query=Fm+towns+free+software+collection)
Ciao!

**Comment by wothke** [comment]
thx. btw I did a quick Web port: http://www.wothke.ch/webEuphony/ 

unfortunately it seems to me that the eupmini emulation isn't that great: many songs complain about 
unimplemented commands and some songs sound horribly out of tune..

do you have and specifications of the .eup file format?

**Comment by gzaffin** [comment]
I know that commands are missing, sorry You discovered lately.
Can You please point a song that sound out of tune? I might look at it.

**Comment by wothke** [comment]
OK. I'll collect the songs that I find during testing.. 

BTW I came across a song that comes in 2 versions - which sound the same as far as I can tell. Diffing the two files shows that the larger version just has an additional inserted block in the middle (while the rest looks pretty identical) - it also has a weird "lauter2" reference : http://www.wothke.ch/tmp/One%20Morning%20[RAM%20IN].zip I wonder what is going on here.. ?
ps: I just saw that a different song from the same author uses a "slauter2" PMB so there is maybe just unused garbage from previous songs in that file?

**Comment by wothke** [comment]
[EUP issues.zip](https://github.com/gzaffin/eupmini/files/12064239/EUP.issues.zip)
here a collection of some files that do not seem to play correctly in eupmini (let's say I'd be surprised to learn that these play how the authors intended..) I did not check if native eupmini actually plays these and it is just my web version that messes something up.. (you can use drag & drop to play files on my above page - but you have to drag&drop the used libs before the song that uses them..)

PS: I played some of the "detuned" songs on eupwin.exe and they sound much better there...

**Comment by wothke** [comment]
[duplibs.zip](https://github.com/gzaffin/eupmini/files/12069967/duplibs.zip)
PS: I notice that same name library files actually exist in different versions (see attached dublibs.zip) and it is possible that some of the songs that sound wrong have just been bundled with incorrect versions of the used libs..

**Comment by gzaffin** [comment]
I need to start looking at Your provided files. I'm going to inform You about any founding.

**Comment by wothke** [comment]
PS: I wonder if it might be a good idea to just replace the existing homegrown emulation with some existing full fledged emulation of the two used chips, e.g. see 2612intf.c and rf5c68.b here: https://bitbucket.org/wothke/vgmplay-0.40.9/src/master/src/chips/ . I guess one would just have to map the player's abstracted "note", "controlChange", "programChange" and "pitchBend" calls to the to the respective lowlevel register changes.

**Comment by wothke** [comment]
> I need to start looking at Your provided files. I'm going to inform You about any founding.

I think "My Feel" and "nemes" are good songs to start with: they use no pitchbend nor unimplemented commands and sound like shit - while eupwin.exe plays them quite OK.

"Kyou2" seems to be a good test case for the flawed "pitchbend" impl. (When adding the following hack in EUPPlayer_cmd_ex the song at  least starts to sound much less shitty: "value = (value - 0x2000)/4 + 0x2000;" i.e. I'd presume that the effect of the  pitchbend used in the original impl  is much to strong and it is probably just implemented incorrectly)

**Comment by wothke** [comment]
nevermind: I patched my version to use the MAME or "Nuked-OPN2" OPN2 emulation and fixed some other issues.. and I am quite happy with how that plays now.

Cheers.

**Comment by gzaffin** [comment]
Hi! I'm sorry I cannot keep pace with You!

What I did these days is researching about missing EUP/MIDI events. It seems to me that I have to serve EUP format channel events of table II-18-5, EUP format system exclusive events of table II-18-6 and EUP format other events of table II-18-7 of [FM TOWNS technical data book](https://archive.org/details/3FmTowns/mode/2up)
![18_4_MIDI_EUPHONY](https://github.com/gzaffin/eupmini/assets/16971874/8697a557-5484-4199-adb2-0324856fdaa3)
this screenshot is for context
![18_4_3_EUP_file_format](https://github.com/gzaffin/eupmini/assets/16971874/5671d80d-4b2f-4972-bd2a-f62709ef7b6a)
here are tables
![18_4_3_EUP_channel_event_system_exclusive_event_meta_event](https://github.com/gzaffin/eupmini/assets/16971874/2c049ad5-7fdf-40a9-84a6-251bbe27cc1d)

I lost a bit of time looking for confirmation about EUP file format in general, without much luck, but I don't see major issue in managing EUP files. I read above that You improved pitchbend. Please share Your findings and code base if You are willing to.

I'm trying to have a more stable reference performace, I don't have a real FM Towns so I chose tsugaru emulator, it should have a modern implementation of Yamaha and Ricoh chips.

A big update should be adding MSV format, it is completely specified. That should be a lot of work though.

That's all for now.
Giangiacomo

**Comment by wothke** [comment]
Regarding the EUP format Tomoaki Hayasaka had pointed me to the "red book" that he had used as a source of information and I have Google translated the respective section here (seem to be the same pages you mention above):

https://bitbucket.org/wothke/webeuphony/src/master/docs/format/eupformat.txt

(You find all my code in that bitbucked repository.)

It seems to me that EUP is basically using MIDI commands and respective MIDI specs are therefore useful where EUP specs are lacking.

I found that there seem to be few unimplemented commands that might actually be relevant (some songs just set some value once to something that would be the default anyway):
- Modulation: (ctrl: 1): according to MIDI this is used to control a vibrato effect (pitch, loudness, brightness) - it is unclear what this should translate to exectly in the EUP context. (testcase: "Just Lucky")
- Sustain Pedal (ctrl: 64): again it is unclear what the EUP specific mapping should look like (testcase: "Bach: Aria on G String")

It would be useful to find out how the "Exclusive status" command's payload data should be interpreted in the EUP context (testcase: "Crocus Garden"). I suspect that it might just be instructions for how to directly set certain chip registers.

Where would you find MSV format songs - how relevant is that format?

**Comment by wothke** [comment]
ps: where did you find the MSV format specs?

**Comment by gzaffin** [comment]
Hi,
for MSV, that is Music SerVer for TOWNS MSV format, You can use following link.
Creator of MSV seems to be Monk Angel VEE03743@nifty.ne.jp (NIFTYSERVE)

[Monk Angel](https://www.vector.co.jp/vpack/browse/person/an010366.html)

Here, click on second link:
●[MSV開発キット(コンソール用)](https://www.vector.co.jp/soft/towns/art/se041219.html)
　コンソール用MSV開発環境

where You can download msvkc250.lzh archive containing DATASHEET.TXT with MSV specifications.
By the way, in the same archive there is MSV.DOC where author says why MSV is relevant, and he also writes pitchbend value problem with EUP that You already found.

There is more about MSV.

You can go to this page about [MSV related tools](http://retropc.net/ryu/unz/lib2.htm)
to get a MSV compiler for Windows 11, plus other stuff.

You can hear about MSV at these links:
[Kanon BGM](https://www.nicovideo.jp/watch/sm32608684)
[Leaf WHITE ALBUM](https://www.nicovideo.jp/watch/sm32015384)
[Thunderforce IV](https://twitter.com/remu_link/status/1436281001630568454)

Some MSV files are at [RopChiptune](http://rophon.music.coocan.jp/chiptune.htm)

All over internet, some more MSV files should be found.

Ciao,
Giangiacomo

**Comment by wothke** [comment]
I just noticed that the PCMTownsPcmEmulator implementation also seems to be badly broken. I suspect that it also might be pitch-bending related. In the attached testcase the song falls totally apart after about 40 seconds creating an awful cacophony. wineup.exe does not have this issue so it not a general EUP but a player issue.
[Spring Landscape.zip](https://github.com/gzaffin/eupmini/files/12196599/Spring.Landscape.zip)

update: you can forget this one... Tomoaki fixed the issue by adding missing _keyOffset handling.. I think that patch also fixed most of the other remaining "detuning" issues that I still had on my watchlist,
[0001-fix-PCM-samplingRate-is-not-adjusted-by-keyOffset-bu.patch](https://github.com/gzaffin/eupmini/files/12206877/0001-fix-PCM-samplingRate-is-not-adjusted-by-keyOffset-bu.patch)

**Comment by gzaffin** [comment]
That's fine though.
Code bases differ now. Once changes they are settled, I'll start importing Your fixes.

**Comment by wothke** [comment]
There is now an extensive "Euphony" folder in the modland collection and I updated my PlayMOD player so that these files can now directly be browsed/played online: see http://www.wothke.ch/playmod/index.php?file=/$Fm%20Towns%20-%20Euphony/&emulator=Euphony

This will likely be my last post on gibhub since I'll no longer use the platform once the morons disable use of my account without their 2-factor authentication garbage..  I'll be on bitbucket for now.

**Comment by gzaffin** [comment]
Thank You Juergen.
I'm going to check for sure Your web app new version and that folder.
I'll keep on eye on that euphony stuff.
Ciao!
