### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by Sembiance** [gzaffin/eupmini#2]
Using the a version of the code from Sep 3, 2023, built on Linux, I get a segfault with the attached [chopin.eup.zip](https://github.com/gzaffin/eupmini/files/12838295/chopin.eup.zip) file.

It plays fine on a version of the code I built from 2021.

Let me know if you can't reproduce it on your side and what additional debug steps you'd like me to take to get you the info you need.

**Comment by gzaffin** [comment]
Could Sembiance try checked-in fix?
Locally I tested with Lubuuntu 20.04 .

**Comment by Sembiance** [comment]
Yes, they now convert without a segfault. Thanks!
